email:
  maximum: 255
micropost:
  maximum_length_content: 255
  maximum_size_picture: 5
password:
  minimum: 6
username:
  maximum: 50
user:
  reset_expired_time: 2
  size_for_gravata_user: 80
  size_for_gravata_user_follow: 30
  size_gravatar_for: 50
  users_per_page: 10
